import { ROLES } from '../../constants/roles';

export const PERMISSIONS = {
  VIEW_DASHBOARD: [ROLES.REGISTRATION_OFFICER, ROLES.ASSESSOR, ROLES.APPROVER, ROLES.ETD_OFFICER, ROLES.ADMIN, ROLES.MANAGEMENT],
  MANAGE_CASES: [ROLES.REGISTRATION_OFFICER, ROLES.ASSESSOR, ROLES.APPROVER, ROLES.ETD_OFFICER, ROLES.ADMIN, ROLES.MANAGEMENT],
  BIOMETRIC_ENROLLMENT: [ROLES.REGISTRATION_OFFICER, ROLES.ASSESSOR, ROLES.ADMIN],
  CONDUCT_ASSESSMENT: [ROLES.ASSESSOR, ROLES.ADMIN],
  MAKE_RECOMMENDATION: [ROLES.ASSESSOR, ROLES.ADMIN],
  DETERMINE_STATUS: [ROLES.APPROVER, ROLES.ADMIN],
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.MANAGEMENT],
  ADMINISTER_SYSTEM: [ROLES.ADMIN],
};

export function hasPermission(role, permissionKey) {
  return PERMISSIONS[permissionKey]?.includes(role) ?? false;
}
